/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import core.Document;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import javax.swing.JToggleButton;
import javax.swing.UIManager;

/**
 * Le fenetre du programme
 *
 * @author francoisr
 */
public class Fenetre extends javax.swing.JFrame {

    public static final Fenetre INSTANCE = new Fenetre();
    private boolean hasEditedText = false;
    
    /**
     * Creates new form Fenetre
     */
    private Fenetre() {
        initComponents();
        
    }

    /**
     * Methode qui indique si on a du texte qui a ete edite mais pas sauvegarde
     *
     * @return true si on a du texte qui a ete edite mais pas sauvegarde
     */
    public boolean hasEditedText() {
        return hasEditedText;
    }
    
    /**
     * Methode pour definir si on a un texte edité ou pas.
     * @param val 
     */
    public void setEdited(boolean val){
        hasEditedText = val;
    }

    public void newDocument(Document document) {
        if (document.getView() == null) {
            document.setView(new TextEditor());
        }
        this.onglets.addTab(document.getTitle(), document.getView());
        // TODO faire correctement l'ajout d'onglet avec le TextEditor
    }

    /**
     * This method is called from within the consturctor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        boutonNouveau = new javax.swing.JButton();
        boutonOuvrir = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        saveAllButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        boldButton = new javax.swing.JToggleButton();
        italicButton = new javax.swing.JToggleButton();
        fontSelector = new javax.swing.JComboBox();
        sizeSelector = new javax.swing.JComboBox();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        writeButton = new javax.swing.JToggleButton();
        crayonButton = new javax.swing.JToggleButton();
        carreButton = new javax.swing.JToggleButton();
        cercleButton = new javax.swing.JToggleButton();
        onglets = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuItemNewFile = new javax.swing.JMenuItem();
        menuItemOpenDocument = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemSave = new javax.swing.JMenuItem();
        saveAsItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuItemGeneratePdf = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemQuitter = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        dessinMenu = new javax.swing.JMenu();
        writeMode = new javax.swing.JRadioButtonMenuItem();
        crayonOption = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        optionMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Notor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setName("fenetre"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        boutonNouveau.setAction(Actions.NEW_DOCUMENT);
        boutonNouveau.setToolTipText("Créer un nouveau document");
        boutonNouveau.setFocusable(false);
        boutonNouveau.setHideActionText(true);
        boutonNouveau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boutonNouveau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boutonNouveau);

        boutonOuvrir.setAction(Actions.OPEN_DOCUMENT);
        boutonOuvrir.setToolTipText("Ouvrir un document");
        boutonOuvrir.setFocusable(false);
        boutonOuvrir.setHideActionText(true);
        boutonOuvrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boutonOuvrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boutonOuvrir);

        saveButton.setAction(Actions.ENREGISTRER);
        saveButton.setToolTipText("Sauvegarde le document en cours");
        saveButton.setFocusable(false);
        saveButton.setHideActionText(true);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(saveButton);

        saveAllButton.setAction(Actions.SAVE_ALL);
        saveAllButton.setToolTipText("Enregistre tout les documents ouverts");
        saveAllButton.setFocusable(false);
        saveAllButton.setHideActionText(true);
        saveAllButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveAllButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(saveAllButton);
        jToolBar1.add(jSeparator3);

        undoButton.setAction(Actions.UNDO);
        undoButton.setToolTipText("Précédent");
        undoButton.setFocusable(false);
        undoButton.setHideActionText(true);
        undoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        undoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(undoButton);

        redoButton.setAction(Actions.REDO);
        redoButton.setToolTipText("Suivant");
        redoButton.setFocusable(false);
        redoButton.setHideActionText(true);
        redoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        redoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(redoButton);
        jToolBar1.add(jSeparator6);

        boldButton.setAction(Actions.BOLD);
        boldButton.setToolTipText("Met le texte selectionné en gras");
        boldButton.setFocusable(false);
        boldButton.setHideActionText(true);
        boldButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boldButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(boldButton);

        italicButton.setAction(Actions.ITALIC);
        italicButton.setToolTipText("Met le texte selectionné en italique");
        italicButton.setFocusable(false);
        italicButton.setHideActionText(true);
        italicButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        italicButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(italicButton);

        fontSelector.setEditable(true);
        fontSelector.setToolTipText("Police de caractère");
        fontSelector.setMaximumSize(new java.awt.Dimension(128, 128));
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String [] polices = ge.getAvailableFontFamilyNames();
        for ( int i = 0 ; i < polices.length ; i++ ){
            fontSelector.addItem(polices[i]);
            if (polices[i].equals("Arial")){
                fontSelector.setSelectedIndex(i);
            }
        }
        jToolBar1.add(fontSelector);

        sizeSelector.setEditable(true);
        sizeSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72" }));
        sizeSelector.setToolTipText("Taille de la police");
        sizeSelector.setMaximumSize(new java.awt.Dimension(64, 64));
        jToolBar1.add(sizeSelector);
        jToolBar1.add(jSeparator4);

        writeButton.setAction(Actions.WRITE_MODE);
        buttonGroup2.add(writeButton);
        writeButton.setSelected(true);
        writeButton.setFocusable(false);
        writeButton.setHideActionText(true);
        writeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        writeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(writeButton);

        crayonButton.setAction(Actions.CRAYON_MODE);
        buttonGroup2.add(crayonButton);
        crayonButton.setFocusable(false);
        crayonButton.setHideActionText(true);
        crayonButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crayonButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(crayonButton);

        carreButton.setAction(Actions.CARRE_MODE);
        buttonGroup2.add(carreButton);
        carreButton.setFocusable(false);
        carreButton.setHideActionText(true);
        carreButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        carreButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(carreButton);

        cercleButton.setAction(Actions.CERCLE_MODE);
        buttonGroup2.add(cercleButton);
        cercleButton.setFocusable(false);
        cercleButton.setHideActionText(true);
        cercleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cercleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cercleButton);

        fileMenu.setMnemonic('F');
        fileMenu.setText("Fichiers");

        menuItemNewFile.setAction(Actions.NEW_DOCUMENT);
        menuItemNewFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        fileMenu.add(menuItemNewFile);

        menuItemOpenDocument.setAction(Actions.OPEN_DOCUMENT);
        fileMenu.add(menuItemOpenDocument);
        fileMenu.add(jSeparator1);

        menuItemSave.setAction(Actions.ENREGISTRER);
        menuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        fileMenu.add(menuItemSave);

        saveAsItem.setAction(Actions.ENREGISTRER_SOUS);
        fileMenu.add(saveAsItem);

        jMenuItem3.setAction(Actions.SAVE_ALL);
        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        fileMenu.add(jMenuItem3);

        menuItemGeneratePdf.setAction(Actions.GENERATE_PDF);
        fileMenu.add(menuItemGeneratePdf);
        fileMenu.add(jSeparator2);

        menuItemQuitter.setAction(Actions.QUITTER);
        menuItemQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        fileMenu.add(menuItemQuitter);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('E');
        editMenu.setText("Editer");

        jMenuItem1.setAction(Actions.BOLD);
        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        editMenu.add(jMenuItem1);

        jMenuItem2.setAction(Actions.ITALIC);
        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        editMenu.add(jMenuItem2);
        editMenu.add(jSeparator5);

        jMenuItem5.setAction(Actions.UNDO);
        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        editMenu.add(jMenuItem5);

        jMenuItem6.setAction(Actions.REDO);
        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        editMenu.add(jMenuItem6);

        menuBar.add(editMenu);

        dessinMenu.setMnemonic('D');
        dessinMenu.setText("Dessin");

        writeMode.setAction(Actions.WRITE_MODE);
        buttonGroup1.add(writeMode);
        writeMode.setSelected(true);
        dessinMenu.add(writeMode);

        crayonOption.setAction(Actions.CRAYON_MODE);
        buttonGroup1.add(crayonOption);
        dessinMenu.add(crayonOption);

        jRadioButtonMenuItem2.setAction(Actions.CERCLE_MODE);
        buttonGroup1.add(jRadioButtonMenuItem2);
        dessinMenu.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem1.setAction(Actions.DISQUE_MODE);
        buttonGroup1.add(jRadioButtonMenuItem1);
        dessinMenu.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem3.setAction(Actions.CARRE_MODE);
        buttonGroup1.add(jRadioButtonMenuItem3);
        dessinMenu.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setAction(Actions.CARRE_PLEIN_MODE);
        buttonGroup1.add(jRadioButtonMenuItem4);
        dessinMenu.add(jRadioButtonMenuItem4);

        jRadioButtonMenuItem5.setAction(Actions.CARRE_ARRONDI_MODE);
        buttonGroup1.add(jRadioButtonMenuItem5);
        dessinMenu.add(jRadioButtonMenuItem5);

        jRadioButtonMenuItem6.setAction(Actions.CARRE_ARRONDI_PLEIN_MODE);
        buttonGroup1.add(jRadioButtonMenuItem6);
        dessinMenu.add(jRadioButtonMenuItem6);

        menuBar.add(dessinMenu);

        optionMenu.setMnemonic('O');
        optionMenu.setText("Options");

        jMenuItem4.setAction(Actions.SHOW_DICTIONNAIRE);
        jMenuItem4.setToolTipText("Configurez le dictionnaire d'abréviations");
        optionMenu.add(jMenuItem4);

        menuBar.add(optionMenu);

        helpMenu.setMnemonic('?');
        helpMenu.setText("?");

        jMenuItem7.setText("Aide");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem7);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
            .addComponent(onglets)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onglets, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Actions.QUITTER.actionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new Aide();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                INSTANCE.setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boldButton;
    private javax.swing.JButton boutonNouveau;
    private javax.swing.JButton boutonOuvrir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JToggleButton carreButton;
    private javax.swing.JToggleButton cercleButton;
    private javax.swing.JToggleButton crayonButton;
    private javax.swing.JRadioButtonMenuItem crayonOption;
    private javax.swing.JMenu dessinMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox fontSelector;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JToggleButton italicButton;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemGeneratePdf;
    private javax.swing.JMenuItem menuItemNewFile;
    private javax.swing.JMenuItem menuItemOpenDocument;
    private javax.swing.JMenuItem menuItemQuitter;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JTabbedPane onglets;
    private javax.swing.JMenu optionMenu;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton saveAllButton;
    private javax.swing.JMenuItem saveAsItem;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox sizeSelector;
    private javax.swing.JButton undoButton;
    private javax.swing.JToggleButton writeButton;
    private javax.swing.JRadioButtonMenuItem writeMode;
    // End of variables declaration//GEN-END:variables

    public JTabbedPane getTabManager() {
        return this.onglets;
    }
    
    public JToggleButton getBoldButton(){
        return this.boldButton;
    }
    
    public JToggleButton getItalicButton(){
        return this.italicButton;
    }
}
